import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";
import dynamic from 'next/dynamic'
import { locales } from "@/navigation";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
const Providers = dynamic(() => import('@/components/providers'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={cn("transition-colors", inter.className)}>
        <Providers locale={locale} messages={messages}>
          <Header />
          <main className="container pb-2 pt-2 md:pt-8 md:pb-8">
            {children}
          </main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
